

services:
  backend:
    build:
      context: ./aws-serverless-app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:

      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN} # Optional: for temporary credentials
      - AWS_REGION=${AWS_REGIOsN:-eu-west-1}
      # These are the default values from your config.js
      - SAP_ATHENA_DB=${SAP_ATHENA_DB:-sap_reports_db}
      - SAP_ATHENA_WORKGROUP=${SAP_ATHENA_WORKGROUP:-ReportCheckSistemiSap}
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # This tells Vite to use a relative path, which Nginx will handle
        - VITE_API_URL=/api 
        # Pass build-time variables for Cognito/Bedrock
        - VITE_COGNITO_USER_POOL_ID=${VITE_COGNITO_USER_POOL_ID}
        - VITE_COGNITO_USER_POOL_CLIENT_ID=${VITE_COGNITO_USER_POOL_CLIENT_ID}
        - VITE_COGNITO_REGION=${VITE_COGNITO_REGION}
        - VITE_COGNITO_IDENTITY_POOL_ID=${VITE_COGNITO_IDENTITY_POOL_ID}
        - VITE_BEDROCK_AGENT_NAME=${VITE_BEDROCK_AGENT_NAME}
        - VITE_BEDROCK_AGENT_ID=${VITE_BEDROCK_AGENT_ID}
        - VITE_BEDROCK_AGENT_ALIAS_ID=${VITE_BEDROCK_AGENT_ALIAS_ID}
        - VITE_BEDROCK_REGION=${VITE_BEDROCK_REGION}
    ports:
      - "8440:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
