version: '3.8'

services:
  # ==========================================
  # FRONTEND - SAP Dashboard
  # ==========================================
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_COGNITO_USER_POOL_ID: "eu-west-1_7WLST1Mlg"
        VITE_COGNITO_USER_POOL_CLIENT_ID: "vpscdsoro31v6hioq7e52ktkv"
        VITE_COGNITO_REGION: "eu-west-1"
        VITE_COGNITO_IDENTITY_POOL_ID: "eu-west-1:36d062f2-d4f0-4b1d-ba60-5ce34cf991cc"
        VITE_BEDROCK_AGENT_NAME: "SAPReportAnalyst"
        VITE_BEDROCK_AGENT_ID: "93BV0V6G4L"
        VITE_BEDROCK_AGENT_ALIAS_ID: "TSTALIASID"
        VITE_BEDROCK_REGION: "eu-west-1"
        VITE_API_URL: "/api"
      platforms:
        - linux/amd64
    container_name: sap-dashboard-frontend-test
    ports:
      - "8080:80"
    networks:
      - sap-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # ==========================================
  # BACKEND - Node.js API (OPZIONALE)
  # Solo se vuoi testare anche il backend
  # ==========================================
  # backend:
  #   build:
  #     context: ./aws-serverless-app
  #     dockerfile: Dockerfile
  #   container_name: sap-backend-test
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3001
  #     - AWS_REGION=eu-west-1
  #   networks:
  #     - sap-network
  #   restart: unless-stopped

networks:
  sap-network:
    driver: bridge